package guru.springframework.module;


import javax.persistence.*;
import java.util.Set;

@Entity
public class Recipe {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // the generation type identity to have autogenerated value in our data-base
    // of course the data base should support this feature .

    private String description;
    private Integer prepTime;
    private Integer cookTime;
    private Integer service;
    private String source;
    private String url ;
    private String direction;
    private Difficulity difficulity;

    @OneToMany(cascade = CascadeType.ALL,mappedBy = "recipe")
    private Set<Ingerediant> ingerediantSet;

    @Lob
    private Byte[] image;
    // when we want jpa support large Byte object without any limitation
    @OneToOne(cascade = CascadeType.ALL)
    private Notes notes;
    // we have one way cascading from Recipe to note

    public Recipe() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getPrepTime() {
        return prepTime;
    }

    public void setPrepTime(Integer prepTime) {
        this.prepTime = prepTime;
    }

    public Integer getCookTime() {
        return cookTime;
    }

    public void setCookTime(Integer cookTime) {
        this.cookTime = cookTime;
    }

    public Integer getService() {
        return service;
    }

    public void setService(Integer service) {
        this.service = service;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public Difficulity getDifficulity() {
        return difficulity;
    }

    public void setDifficulity(Difficulity difficulity) {
        this.difficulity = difficulity;
    }

    public Byte[] getImage() {
        return image;
    }

    public void setImage(Byte[] image) {
        this.image = image;
    }

    public Notes getNotes() {
        return notes;
    }

    public void setNotes(Notes notes) {
        this.notes = notes;
    }

    public Set<Ingerediant> getIngerediantSet() {
        return ingerediantSet;
    }

    public void setIngerediantSet(Set<Ingerediant> ingerediantSet) {
        this.ingerediantSet = ingerediantSet;
    }
}
